"""empty message

Revision ID: 1293e1598f4b
Revises: 84f1979f6397
Create Date: 2021-04-09 12:26:20.693835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1293e1598f4b'
down_revision = '84f1979f6397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('answer', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('present', sa.Integer(), nullable=False))
    op.drop_column('students', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('students', 'present')
    op.drop_column('students', 'answer')
    # ### end Alembic commands ###
