"""empty message

Revision ID: 54271720cb30
Revises: 
Create Date: 2021-04-01 13:06:58.075965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54271720cb30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.String(length=13), nullable=False),
    sa.Column('course_name', sa.String(length=32), nullable=False),
    sa.Column('teacher_id', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('course_id', 'teacher_id')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=True)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=True)
    op.create_table('stu_courses',
    sa.Column('uid', sa.String(length=13), nullable=False),
    sa.Column('course_id', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'course_id')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=13), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('stu_courses')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
