"""empty message

Revision ID: 84f1979f6397
Revises: e866580ddbed
Create Date: 2021-04-07 14:58:41.618430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f1979f6397'
down_revision = 'e866580ddbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_teacher_id', table_name='courses')
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.create_index('ix_courses_teacher_id', 'courses', ['teacher_id'], unique=True)
    # ### end Alembic commands ###
